# Generated by Django 3.0.6 on 2020-06-07 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usr', '0002_auto_20200607_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_set_name', models.CharField(max_length=30)),
                ('max_papers', models.CharField(max_length=2)),
                ('create_timestamp', models.DateTimeField(max_length=20)),
                ('expiry_timestamp', models.DateTimeField(max_length=30)),
                ('active_flag', models.CharField(max_length=2)),
                ('fk_cus_grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.CusGroup')),
                ('fk_exam_set_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Customers')),
                ('fk_host_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.CusRoot')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('culture', models.CharField(max_length=15)),
                ('short_description', models.CharField(max_length=8)),
                ('subject_code', models.CharField(max_length=10)),
                ('entry_status', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_level_name', models.CharField(max_length=30)),
                ('topic_level_value', models.CharField(max_length=30)),
                ('topic_num_on_level', models.CharField(max_length=30)),
                ('topic_name', models.CharField(max_length=20)),
                ('creation_dt', models.DateField(max_length=26)),
                ('tackles_total', models.CharField(max_length=20)),
                ('tackles_failed', models.CharField(max_length=20)),
                ('tough_scale', models.CharField(max_length=2)),
                ('entry_status', models.CharField(max_length=15)),
                ('fk_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('correct_ans_desc', models.CharField(max_length=150)),
                ('has_diag_flg', models.CharField(max_length=4)),
                ('has_diag_url', models.CharField(max_length=50)),
                ('has_more_ans_flg', models.CharField(max_length=2)),
                ('reviewed_times', models.CharField(max_length=2)),
                ('relates_to_other_que', models.CharField(max_length=2)),
                ('relates_to_other_pos', models.CharField(max_length=2)),
                ('tackles_total', models.CharField(max_length=20)),
                ('tackles_failed', models.CharField(max_length=20)),
                ('tough_scale', models.CharField(max_length=2)),
                ('marks_allocated', models.CharField(max_length=2)),
                ('creation_dt', models.DateField(max_length=30)),
                ('update_dt', models.DateField(max_length=30)),
                ('fk_updater_by', models.DateField(max_length=30)),
                ('fk_updater_host', models.DateField(max_length=30)),
                ('fk_created_usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Customers')),
                ('fk_creator_host_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.CusRoot')),
                ('fk_topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='QAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_position', models.CharField(max_length=4)),
                ('correct_flg', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=100)),
                ('ans_is_diag_flg', models.CharField(max_length=2)),
                ('ans_is_diag_url', models.CharField(max_length=50)),
                ('fk_que_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Quests')),
            ],
        ),
        migrations.CreateModel(
            name='MarkedPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_num_on_paper', models.CharField(max_length=2)),
                ('max_ques_on_pp', models.CharField(max_length=2)),
                ('mark_result', models.CharField(max_length=1)),
                ('marks_given', models.CharField(max_length=2)),
                ('answer_id_given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.QAnswers')),
                ('fk_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Customers')),
                ('fk_exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.ExamSet')),
                ('fk_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Subjects')),
                ('quests_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Quests')),
            ],
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_num_on_paper', models.CharField(max_length=2)),
                ('max_ques_on_pp', models.CharField(max_length=2)),
                ('create_timestamp', models.DateTimeField(max_length=20)),
                ('expiry_timestamp', models.DateTimeField(max_length=30)),
                ('active_flag', models.CharField(max_length=2)),
                ('fk_exam_pp_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Customers')),
                ('fk_exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.ExamSet')),
                ('fk_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Subjects')),
                ('quests_sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmt.Quests')),
            ],
        ),
    ]
