# Generated by Django 3.0.6 on 2020-06-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='subject_for_level_name',
            field=models.CharField(default='Primary', max_length=20),
            preserve_default=False,
        ),
    ]
