# Generated by Django 3.0.6 on 2020-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0002_subjects_subject_for_level_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quests',
            old_name='fk_topic_id',
            new_name='fk_topic',
        ),
        migrations.AlterField(
            model_name='quests',
            name='fk_updater_by',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='quests',
            name='fk_updater_host',
            field=models.CharField(max_length=30),
        ),
    ]
