# Generated by Django 3.0.6 on 2020-06-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0003_auto_20200607_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qanswers',
            old_name='fk_que_id',
            new_name='fk_que',
        ),
        migrations.AddField(
            model_name='quests',
            name='review_sts',
            field=models.CharField(default='0', max_length=2),
            preserve_default=False,
        ),
    ]
