# Generated by Django 3.0.6 on 2020-06-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmt', '0004_auto_20200607_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='markedpapers',
            name='que_rated_flag',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markedpapers',
            name='topic_rated_flag',
            field=models.CharField(default='0', max_length=1),
            preserve_default=False,
        ),
    ]
