# Generated by Django 3.0.6 on 2020-06-06 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CusRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('contact_cus', models.CharField(max_length=20)),
                ('creation_dt', models.DateField(max_length=26)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('entry_status', models.CharField(max_length=30)),
                ('org_type', models.CharField(max_length=30)),
                ('org_status', models.CharField(max_length=30)),
                ('sales_rep_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CusRootTrx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ref_id', models.CharField(max_length=30)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('curr_month', models.CharField(max_length=2)),
                ('sub_status', models.CharField(max_length=2)),
                ('created_by', models.CharField(max_length=20)),
                ('creation_dt', models.DateField(max_length=30)),
                ('updated_by', models.CharField(max_length=20)),
                ('update_dt', models.DateField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=30)),
                ('max_cus_1', models.CharField(max_length=15)),
                ('max_cus_2', models.CharField(max_length=5)),
                ('max_groups', models.CharField(max_length=10)),
                ('pay_curr', models.CharField(max_length=5)),
                ('payable_amount', models.CharField(max_length=13)),
                ('pay_duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=30)),
                ('creation_dt', models.DateField(max_length=30)),
                ('kyc_flag', models.CharField(max_length=1)),
                ('has_doc_type', models.CharField(max_length=1)),
                ('has_doc_value', models.CharField(max_length=1)),
                ('has_org_type', models.CharField(max_length=2)),
                ('has_class_code', models.CharField(max_length=10)),
                ('has_other_class_flg', models.CharField(max_length=2)),
                ('entry_status', models.CharField(max_length=2)),
                ('cus_type', models.CharField(max_length=2)),
                ('cus_status', models.CharField(max_length=2)),
                ('has_badge', models.CharField(max_length=20)),
                ('has_org_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.CusRoot')),
            ],
        ),
        migrations.CreateModel(
            name='CusRootSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_ref_id', models.CharField(max_length=30)),
                ('fiscal_year', models.CharField(max_length=4)),
                ('curr_month', models.CharField(max_length=2)),
                ('sub_status', models.CharField(max_length=2)),
                ('created_by', models.CharField(max_length=20)),
                ('creation_dt', models.DateField(max_length=30)),
                ('updated_by', models.CharField(max_length=20)),
                ('update_dt', models.DateField(max_length=30)),
                ('fk_root_cus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.CusRoot')),
            ],
        ),
        migrations.AddField(
            model_name='cusroot',
            name='fk_pack_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.Packages'),
        ),
        migrations.CreateModel(
            name='CusRelates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_type', models.CharField(max_length=20)),
                ('create_timestamp', models.DateTimeField(max_length=20)),
                ('expiry_timestamp', models.DateTimeField(max_length=30)),
                ('entry_status', models.CharField(max_length=2)),
                ('child_cus', models.ManyToManyField(to='usr.Customers')),
                ('parent_cus', models.ManyToManyField(to='usr.CusRoot')),
            ],
        ),
        migrations.CreateModel(
            name='CusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(max_length=30)),
                ('grp_type', models.CharField(max_length=30)),
                ('grp_level_name', models.CharField(max_length=30)),
                ('grp_level_value', models.CharField(max_length=30)),
                ('fk_cus_created_grp', models.CharField(max_length=30)),
                ('grp_create_dt', models.DateField(max_length=30)),
                ('grp_expire_dt', models.DateField(max_length=30)),
                ('entry_status', models.CharField(max_length=30)),
                ('fk_cus_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usr.CusRoot')),
            ],
        ),
    ]
