# Generated by Django 3.0.6 on 2020-06-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='has_doc_value',
            field=models.CharField(max_length=26),
        ),
    ]
