# Generated by Django 3.0.6 on 2020-06-13 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usr', '0002_auto_20200607_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='user',
            field=models.OneToOneField(default='2', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='packages',
            name='description',
            field=models.CharField(default='This is arguably the best package for your need', max_length=50),
            preserve_default=False,
        ),
    ]
